{
  "formatVersion": "1.1",
  "component": {
    "group": "com.harisdautovic",
    "module": "github-playground-sdk",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "github-playground-sdk-0.0.3.jar",
          "url": "github-playground-sdk-0.0.3.jar",
          "size": 1411,
          "sha512": "1f6462f843dcaa053572e18025d754d4cac14ed33eb107bf1f0c8f07ad3401c224048bfd8db4b794ea7b774054940b43b3b260fa32591c287b5c2d99783fc6f6",
          "sha256": "126c2f2d6bb647c6f1c1c75f549780a4a1f37ebf8ad3a7871f698ee48bccdc14",
          "sha1": "abb69bd2c572ea5b1e642c3d28053110d896a330",
          "md5": "4fe370194d7f259097e5ed9dccfa18b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "github-playground-sdk-0.0.3.jar",
          "url": "github-playground-sdk-0.0.3.jar",
          "size": 1411,
          "sha512": "1f6462f843dcaa053572e18025d754d4cac14ed33eb107bf1f0c8f07ad3401c224048bfd8db4b794ea7b774054940b43b3b260fa32591c287b5c2d99783fc6f6",
          "sha256": "126c2f2d6bb647c6f1c1c75f549780a4a1f37ebf8ad3a7871f698ee48bccdc14",
          "sha1": "abb69bd2c572ea5b1e642c3d28053110d896a330",
          "md5": "4fe370194d7f259097e5ed9dccfa18b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-playground-sdk-0.0.3-javadoc.jar",
          "url": "github-playground-sdk-0.0.3-javadoc.jar",
          "size": 261,
          "sha512": "de9186556d48b1fce327767354a2fa58b98d739672285c939dd08e020fe28c2667d89acf4837e6c6f9a6d421b776b7c8b77f03f9f8a84140d9f7ee4766a12eef",
          "sha256": "0b848e86b182d275c7007e5c7fa7fd24c816b83fb7587c6874de6caf8a07a5b4",
          "sha1": "787c9ccd7205bfd1746ec7bbcf2af9a4d3a6e9d5",
          "md5": "cb66e81b4df7b4587f8e2613467ea8d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-playground-sdk-0.0.3-sources.jar",
          "url": "github-playground-sdk-0.0.3-sources.jar",
          "size": 857,
          "sha512": "31c3e85a5952005fbf42568440dfad3c2488980eaf00890c08b005ca8b7398346389fa96e4c6ad6f73ccaa1e4169d60bbc4573e34e89b48f90e54ef3e4afb3b7",
          "sha256": "2115adbb2918d03ae3d136331828b4543b75c5446eae5e99822fe2046f449b00",
          "sha1": "705d2413403c353db7ef8a5653add2d8e00fb427",
          "md5": "dd777c288b03fe3a89d9f83f06d3c436"
        }
      ]
    }
  ]
}
